### ISSUE TITLE
[Feature Request / Suggestion]: containerize Ambi and the Postgresql instance for easier deployments

### ISSUE THREAD

**Issue by jhodapp** [Jim-Hodapp-Coaching/ambi-rs#17]
### Suggestion / Feature Request

This feature request is about containerizing Ambi so that:
1. It's much easier to get a new developer up and working with Ambi-rs without much local dev machine effort
2. It's easy to deploy and run an instance of Ambi-rs and the correct version of Postgresql

### TODOs

- [x] Ensure that running the project outside of Docker works
- [x] Configure `database.url` through environment variables
- [x] Add an automated build and publish step in the current workflow 
- [ ] ~Optimize the image~ We might revisit this when we want to use the image in production. Currently it is only meant for development.
